name: 'Deploy PACKAGE.broker to Cloudflare Workers'
description: 'Deploy PACKAGE.broker to Cloudflare Workers with automated resource creation and configuration'
branding:
  icon: 'cloud'
  color: 'blue'
inputs:
  cloudflare_api_token:
    description: 'Cloudflare API token with Workers, D1, KV, R2, and Queues permissions'
    required: true
  cloudflare_account_id:
    description: 'Cloudflare account ID'
    required: true
  encryption_key:
    description: 'Base64-encoded encryption key for PACKAGE.broker'
    required: true
  working_directory:
    description: 'Directory containing package.json / package-lock.json / wrangler.toml (relative to repository root)'
    required: false
    default: '.'
  worker_name:
    description: 'Worker name (defaults to repository name)'
    required: false
    default: ''
  tier:
    description: 'Cloudflare Workers tier: free or paid'
    required: false
    default: 'free'
  node_version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  skip_ui_build:
    description: 'Skip UI build if pre-built assets are available'
    required: false
    default: 'false'
  skip_migrations:
    description: 'Skip migration application'
    required: false
    default: 'false'
  domain:
    description: 'Custom domain to use (e.g., app.example.com). Adds route configuration. User must manually create CNAME record.'
    required: false
    default: ''
outputs:
  worker_url:
    description: 'Deployed Worker URL'
  database_id:
    description: 'Created or found D1 database ID'
  kv_namespace_id:
    description: 'Created or found KV namespace ID'
runs:
  using: 'composite'
  steps:
    - name: Validate required configuration
      shell: bash
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare_api_token }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.cloudflare_account_id }}
        ENCRYPTION_KEY: ${{ inputs.encryption_key }}
      run: |
        set -euo pipefail

        missing=0
        require() {
          local name="$1"
          if [ -z "${!name:-}" ]; then
            echo "::error::Missing required ${name}. Set it in GitHub Settings → Secrets and variables → Actions."
            missing=1
          fi
        }

        require CLOUDFLARE_API_TOKEN
        require CLOUDFLARE_ACCOUNT_ID
        require ENCRYPTION_KEY

        if [ "${missing}" -ne 0 ]; then
          exit 1
        fi

    - name: Resolve working directory
      id: workdir
      shell: bash
      env:
        INPUT_WORKDIR: ${{ inputs.working_directory }}
      run: |
        set -euo pipefail

        WORKDIR="${INPUT_WORKDIR:-.}"
        if [ -z "$WORKDIR" ]; then
          WORKDIR="."
        fi

        if [ ! -d "$WORKDIR" ]; then
          echo "::error::working_directory '${WORKDIR}' does not exist in the repository workspace."
          echo "::error::Set 'working_directory' to the folder that contains your package.json."
          exit 1
        fi

        echo "path=${WORKDIR}" >> "$GITHUB_OUTPUT"
        echo "Using working directory: ${WORKDIR}"

    - name: Require package-lock.json
      shell: bash
      working-directory: ${{ steps.workdir.outputs.path }}
      run: |
        set -euo pipefail

        if [ ! -f "package-lock.json" ]; then
          echo "::error::package-lock.json is required but not found in '${{ steps.workdir.outputs.path }}'."
          echo "::error::This action requires an initialized repository with committed package.json and package-lock.json."
          echo "::error::Run 'npm install' locally and commit both files before using this action."
          exit 1
        fi

        if [ ! -f "package.json" ]; then
          echo "::error::package.json is required but not found in '${{ steps.workdir.outputs.path }}'."
          echo "::error::Commit package.json and package-lock.json before using this action."
          exit 1
        fi

        echo "✓ Found package.json and package-lock.json"

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'npm'
        cache-dependency-path: ${{ steps.workdir.outputs.path }}/package-lock.json

    - name: Install dependencies
      shell: bash
      working-directory: ${{ steps.workdir.outputs.path }}
      run: |
        set -euo pipefail
        echo "Installing dependencies with npm ci..."
        npm ci

    - name: Determine worker name
      id: worker_name
      shell: bash
      env:
        INPUT_WORKER_NAME: ${{ inputs.worker_name }}
        REPO_NAME: ${{ github.event.repository.name }}
      run: |
        if [ -n "${INPUT_WORKER_NAME}" ]; then
          WORKER_NAME="${INPUT_WORKER_NAME}"
        else
          WORKER_NAME="${REPO_NAME}"
        fi
        echo "name=${WORKER_NAME}" >> $GITHUB_OUTPUT
        echo "Using worker name: ${WORKER_NAME}"

    - name: Deploy via CLI
      id: deploy
      shell: bash
      working-directory: ${{ steps.workdir.outputs.path }}
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare_api_token }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.cloudflare_account_id }}
        ENCRYPTION_KEY: ${{ inputs.encryption_key }}
        WORKER_NAME: ${{ steps.worker_name.outputs.name }}
        CLOUDFLARE_TIER: ${{ inputs.tier }}
        DOMAIN: ${{ inputs.domain }}
        SKIP_UI_BUILD: ${{ inputs.skip_ui_build }}
        SKIP_MIGRATIONS: ${{ inputs.skip_migrations }}
        CI: 'true'
      run: |
        set -euo pipefail

        # Build CLI command arguments
        CLI_ARGS=("deploy" "--ci" "--json")
        
        if [ -n "${WORKER_NAME:-}" ]; then
          CLI_ARGS+=("--worker-name" "${WORKER_NAME}")
        fi
        
        if [ -n "${CLOUDFLARE_TIER:-}" ]; then
          CLI_ARGS+=("--tier" "${CLOUDFLARE_TIER}")
        fi
        
        if [ -n "${DOMAIN:-}" ]; then
          CLI_ARGS+=("--domain" "${DOMAIN}")
        fi
        
        if [ "${SKIP_UI_BUILD:-false}" = "true" ]; then
          CLI_ARGS+=("--skip-ui-build")
        fi
        
        if [ "${SKIP_MIGRATIONS:-false}" = "true" ]; then
          CLI_ARGS+=("--skip-migrations")
        fi

        # Run CLI and capture JSON output
        echo "Running: npx --no-install package-broker-cloudflare ${CLI_ARGS[*]}"
        JSON_OUTPUT=$(npx --no-install package-broker-cloudflare "${CLI_ARGS[@]}" 2>&1) || {
          EXIT_CODE=$?
          echo "::error::CLI deployment failed with exit code ${EXIT_CODE}"
          echo "::error::CLI output: ${JSON_OUTPUT}"
          exit ${EXIT_CODE}
        }

        # Extract JSON from output (may have GitHub annotations mixed in)
        # The CLI outputs JSON on stdout when --json is used, but may also emit GitHub annotations
        # Try to find the JSON object (starts with { and ends with })
        JSON_ONLY=$(echo "$JSON_OUTPUT" | grep -oE '\{[^}]*"worker_url"[^}]*\}' | head -1 || echo "$JSON_OUTPUT" | grep -E '^\s*\{' | head -1 || echo "$JSON_OUTPUT" | tail -1)
        
        # Parse JSON and set outputs (jq is available in GitHub Actions runners)
        WORKER_URL=$(echo "$JSON_ONLY" | jq -r '.worker_url // empty' 2>/dev/null || echo "")
        DATABASE_ID=$(echo "$JSON_ONLY" | jq -r '.database_id // empty' 2>/dev/null || echo "")
        KV_NAMESPACE_ID=$(echo "$JSON_ONLY" | jq -r '.kv_namespace_id // empty' 2>/dev/null || echo "")
        
        # Validate we got at least the worker URL
        if [ -z "$WORKER_URL" ] && [ -z "$(echo "$JSON_ONLY" | jq -r '.error // empty' 2>/dev/null)" ]; then
          echo "::warning::Could not parse JSON output from CLI. Raw output:"
          echo "$JSON_OUTPUT"
        fi

        if [ -n "$WORKER_URL" ]; then
          echo "worker_url=${WORKER_URL}" >> $GITHUB_OUTPUT
        fi
        if [ -n "$DATABASE_ID" ]; then
          echo "database_id=${DATABASE_ID}" >> $GITHUB_OUTPUT
        fi
        if [ -n "$KV_NAMESPACE_ID" ]; then
          echo "kv_namespace_id=${KV_NAMESPACE_ID}" >> $GITHUB_OUTPUT
        fi

    - name: Display deployment results
      shell: bash
      env:
        WORKER_URL: ${{ steps.deploy.outputs.worker_url }}
        DOMAIN: ${{ inputs.domain }}
      run: |
        if [ -n "${WORKER_URL:-}" ]; then
          echo "::notice::✅ Deployment complete!"
          echo "::notice::🌐 Worker URL: ${WORKER_URL}"
          
          if [ -n "${DOMAIN:-}" ]; then
            echo ""
            echo "::notice::🌐 Custom Domain Configuration Required"
            echo "::notice::Create a CNAME record in Cloudflare DNS pointing ${DOMAIN} to ${WORKER_URL}"
          fi
        fi
